version: '3'
services:
  app-bayeta:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - bayeta-network
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - bayeta-network
    volumes:
      - mongodb-data:/data/db
networks:
  bayeta-network:

volumes:
  mongodb-data:
